// web3 is an Ethereum client library
import Web3 from 'web3';
const web3 = new Web3();

/*
 *  Login API.
 */
var LoginConnectionInstance = {
    /**
     * Connect to the Login contract.
     */
    ConnectToLoginContract: function (url='http://localhost:8545') {
        try {
            web3.setProvider(new web3.providers.HttpProvider(url));

            // This file is generated by the Solidity compiler to easily interact with
            // the contract using the web3 library.
            const loginAbi = require('../contracts/Login.json').abi;
            const LoginConnector = web3.eth.contract(loginAbi);
        }

        catch (e) {
            console.error("Could not connect to login contract. Error: ", ex);
        }

        finally {
            // cleanup
        }
    },

};

export default LoginConnectionInstance;
